#pragma once

const char* vert_shader =
    "#version 450 core\n"
    "layout(location = 0) in vec2 aPos;\n"
    "layout(location = 1) in vec2 aUV;\n"
    "layout(location = 2) in vec4 aColor;\n"
    "\n"
    "layout(push_constant) uniform uPushConstant {\n"
    "    vec2 uScale;\n"
    "    vec2 uTranslate;\n"
    "} pc;\n"
    "\n"
    "out gl_PerVertex {\n"
    "    vec4 gl_Position;\n"
    "};\n"
    "\n"
    "layout(location = 0) out struct {\n"
    "    vec4 Color;\n"
    "    vec2 UV;\n"
    "} Out;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    Out.Color = aColor;\n"
    "    Out.UV = aUV;\n"
    "    gl_Position = vec4(aPos * pc.uScale + pc.uTranslate, 0, 1);\n"
    "}";

const char* frag_shader =
    "#version 450 core\n"
    "layout(location = 0) out vec4 fColor;\n"
    "\n"
    "layout(set=0, binding=0) uniform sampler2D sTexture;\n"
    "\n"
    "layout(location = 0) in struct {\n"
    "    vec4 Color;\n"
    "    vec2 UV;\n"
    "} In;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    fColor = In.Color * texture(sTexture, In.UV.st);\n"
    "}";
